const {StyleSheet} = require('react-native');

export const RegisterStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#121724',
    minHeight: 800,
  },
  title: {
    color: '#fff',
    borderRadius: 5,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 16,
    borderColor: '#556080',
    borderBottomWidth: 1,
    borderBottomColor: '#3ABEFE',
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 10,
    width: 315,
  },
  logo: {
    width: '80%',
    height: 55,
    marginTop: 30,
    marginBottom: 22,
    padding: 10,
  },
  subTitle: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    marginBottom: 20,
    color: 'grey',
    textAlign: 'center',
  },

  input: {
    borderBottomWidth: 2,
    borderBottomColor: '#3ABEFE',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    padding: 10,
    marginBottom: 8,
    zIndex: -1000,
    color: '#fff',
  },
  form: {
    width: 330,
  },
  button: {
    backgroundColor: '#0C538C',
    paddingVertical: 10,
    paddingHorizontal: 20,
    fontFamily: 'RussoOne-Regular',
    marginBottom: 20,
    width: '50%',
    alignItems: 'center',
    marginTop: 50,
    textAlign: 'center',
    justifyContent: 'center',
    //Shadow
    shadowColor: '#3ABEFE',
    shadowOffset: {
      //small light shadow
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#4D515B',
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'RussoOne-Regular',
    fontWeight: '900',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    width: 320,
  },
  link: {
    color: '#3ABEFE',
    textDecorationLine: 'underline',
    fontWeight: '900',
  },
  bottom: {
    flexDirection: 'row',
  },
  bottomText: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  ForgetPass: {
    color: '#FFFFFF',
    fontWeight: '400',
    marginRight: 150,
  },
  Logos: {
    flexDirection: 'row',
    marginTop: 35,
  },
  loginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  loginText: {
    color: '#fff',
    fontSize: 14,
    marginRight: 5,
  },
  loginButton: {
    color: '#3ABEFE',
    fontSize: 14,
    fontWeight: 'bold',
  },
  error: {
    color: 'red',
    fontSize: 14,
    marginTop: 5,
    fontFamily: 'Poppins-Bold',
    fontWeight: 800,
    textAlign: 'left',
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  closeButton: {
    backgroundColor: '#2196F3',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    color: '#000',
  },

  genderInput: {
    borderBottomWidth: 2,
    borderBottomColor: '#3ABEFE',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    padding: 10,
    marginBottom: 8,
    zIndex: -1000,
    color: '#fff',
  },

  FacebookLogo: {
    backgroundColor: '#385B91',
    borderRadius: 4,
    alignItems: 'center',
    flexDirection: 'row',
    padding: 10,
    marginRight: 10,
  },
  GoogleLogo: {
    backgroundColor: '#D13123',
    borderRadius: 4,
    alignItems: 'center',
    flexDirection: 'row',
    padding: 10,
    width: 105,
  },
  Or: {
    color: '#fff',
    fontFamily: 'RussoOne-Regular',
    fontSize: 16,
    marginLeft: 10,
    marginRight: 10,
  },
});
